ERROR com.shatura.bc.tmfirst.TerminalSession.run(TerminalSession.java:317) - [01.09.2015 21:05:53]: run()
ru.sns.UnexpectedNestedException: Error while opening connection to wrk;  raiser: ru.sns.db.defined.apps.DatabaseApplEnv$DAEConnFactory, value=ru.sns.db.defined.apps.DatabaseApplEnv$DAEConnFactory@121964c for database named wrk, NESTED: java.sql.SQLException: Io exception: The Network Adapter could not establish the connectionjava.sql.SQLException: Io exception: The Network Adapter could not establish the connection at:
java.sql.SQLException: Io exception: The Network Adapter could not establish the connection
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:112)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:146)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:255)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:387)
	at oracle.jdbc.driver.PhysicalConnection.<init>(PhysicalConnection.java:420)
	at oracle.jdbc.driver.T4CConnection.<init>(T4CConnection.java:165)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:35)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:801)
	at java.sql.DriverManager.getConnection(DriverManager.java:571)
	at java.sql.DriverManager.getConnection(DriverManager.java:215)
	at ru.sns.db.CustConnFactory.getConnection(CustConnFactory.java:101)
	at ru.sns.db.defined.PredefinedConnFactory.open(PredefinedConnFactory.java:352)
	at ru.sns.db.defined.PredefinedConnection.getConnection(PredefinedConnection.java:106)
	at ru.sns.db.defined.DefaultPredefinedConnUser.getConnection(DefaultPredefinedConnUser.java:58)
	at com.shatura.bc.tmfirst.data.db.DataCache.registerSession(DataCache.java:33)
	at com.shatura.bc.tmfirst.logic.DBOpers.registerSession(DBOpers.java:72)
	at com.shatura.bc.tmfirst.logic.acts.GoToMainMenuAction.perform(GoToMainMenuAction.java:21)
	at com.shatura.bc.tmfirst.logic.states.InitialTerminalSessionState.doActionByData(InitialTerminalSessionState.java:28)
	at com.shatura.bc.tmfirst.logic.states.AbstractTerminalSessionState.processData(AbstractTerminalSessionState.java:52)
	at com.shatura.bc.tmfirst.logic.LogicProcessor.process(LogicProcessor.java:70)
	at com.shatura.bc.tmfirst.TerminalSession.run(TerminalSession.java:313)
	at net.wimpi.telnetd.net.Connection.run(Connection.java:125)

	at ru.sns.db.defined.PredefinedConnFactory.open(PredefinedConnFactory.java:354)
	at ru.sns.db.defined.PredefinedConnection.getConnection(PredefinedConnection.java:106)
	at ru.sns.db.defined.DefaultPredefinedConnUser.getConnection(DefaultPredefinedConnUser.java:58)
	at com.shatura.bc.tmfirst.data.db.DataCache.registerSession(DataCache.java:33)
	at com.shatura.bc.tmfirst.logic.DBOpers.registerSession(DBOpers.java:72)
	at com.shatura.bc.tmfirst.logic.acts.GoToMainMenuAction.perform(GoToMainMenuAction.java:21)
	at com.shatura.bc.tmfirst.logic.states.InitialTerminalSessionState.doActionByData(InitialTerminalSessionState.java:28)
	at com.shatura.bc.tmfirst.logic.states.AbstractTerminalSessionState.processData(AbstractTerminalSessionState.java:52)
	at com.shatura.bc.tmfirst.logic.LogicProcessor.process(LogicProcessor.java:70)
	at com.shatura.bc.tmfirst.TerminalSession.run(TerminalSession.java:313)
	at net.wimpi.telnetd.net.Connection.run(Connection.java:125)
Caused by: java.sql.SQLException: Io exception: The Network Adapter could not establish the connection
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:112)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:146)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:255)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:387)
	at oracle.jdbc.driver.PhysicalConnection.<init>(PhysicalConnection.java:420)
	at oracle.jdbc.driver.T4CConnection.<init>(T4CConnection.java:165)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:35)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:801)
	at java.sql.DriverManager.getConnection(DriverManager.java:571)
	at java.sql.DriverManager.getConnection(DriverManager.java:215)
	at ru.sns.db.CustConnFactory.getConnection(CustConnFactory.java:101)
	at ru.sns.db.defined.PredefinedConnFactory.open(PredefinedConnFactory.java:352)
	... 10 more
ERROR com.shatura.bc.tmfirst.TerminalSession.run(TerminalSession.java:317) - [01.09.2015 21:06:32]: run()
ru.sns.UnexpectedNestedException: Error while opening connection to wrk;  raiser: ru.sns.db.defined.apps.DatabaseApplEnv$DAEConnFactory, value=ru.sns.db.defined.apps.DatabaseApplEnv$DAEConnFactory@121964c for database named wrk, NESTED: java.sql.SQLException: Io exception: The Network Adapter could not establish the connectionjava.sql.SQLException: Io exception: The Network Adapter could not establish the connection at:
java.sql.SQLException: Io exception: The Network Adapter could not establish the connection
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:112)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:146)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:255)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:387)
	at oracle.jdbc.driver.PhysicalConnection.<init>(PhysicalConnection.java:420)
	at oracle.jdbc.driver.T4CConnection.<init>(T4CConnection.java:165)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:35)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:801)
	at java.sql.DriverManager.getConnection(DriverManager.java:571)
	at java.sql.DriverManager.getConnection(DriverManager.java:215)
	at ru.sns.db.CustConnFactory.getConnection(CustConnFactory.java:101)
	at ru.sns.db.defined.PredefinedConnFactory.open(PredefinedConnFactory.java:352)
	at ru.sns.db.defined.PredefinedConnection.getConnection(PredefinedConnection.java:106)
	at ru.sns.db.defined.DefaultPredefinedConnUser.getConnection(DefaultPredefinedConnUser.java:58)
	at com.shatura.bc.tmfirst.data.db.DataCache.registerSession(DataCache.java:33)
	at com.shatura.bc.tmfirst.logic.DBOpers.registerSession(DBOpers.java:72)
	at com.shatura.bc.tmfirst.logic.acts.GoToMainMenuAction.perform(GoToMainMenuAction.java:21)
	at com.shatura.bc.tmfirst.logic.states.InitialTerminalSessionState.doActionByData(InitialTerminalSessionState.java:28)
	at com.shatura.bc.tmfirst.logic.states.AbstractTerminalSessionState.processData(AbstractTerminalSessionState.java:52)
	at com.shatura.bc.tmfirst.logic.LogicProcessor.process(LogicProcessor.java:70)
	at com.shatura.bc.tmfirst.TerminalSession.run(TerminalSession.java:313)
	at net.wimpi.telnetd.net.Connection.run(Connection.java:125)

	at ru.sns.db.defined.PredefinedConnFactory.open(PredefinedConnFactory.java:354)
	at ru.sns.db.defined.PredefinedConnection.getConnection(PredefinedConnection.java:106)
	at ru.sns.db.defined.DefaultPredefinedConnUser.getConnection(DefaultPredefinedConnUser.java:58)
	at com.shatura.bc.tmfirst.data.db.DataCache.registerSession(DataCache.java:33)
	at com.shatura.bc.tmfirst.logic.DBOpers.registerSession(DBOpers.java:72)
	at com.shatura.bc.tmfirst.logic.acts.GoToMainMenuAction.perform(GoToMainMenuAction.java:21)
	at com.shatura.bc.tmfirst.logic.states.InitialTerminalSessionState.doActionByData(InitialTerminalSessionState.java:28)
	at com.shatura.bc.tmfirst.logic.states.AbstractTerminalSessionState.processData(AbstractTerminalSessionState.java:52)
	at com.shatura.bc.tmfirst.logic.LogicProcessor.process(LogicProcessor.java:70)
	at com.shatura.bc.tmfirst.TerminalSession.run(TerminalSession.java:313)
	at net.wimpi.telnetd.net.Connection.run(Connection.java:125)
Caused by: java.sql.SQLException: Io exception: The Network Adapter could not establish the connection
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:112)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:146)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:255)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:387)
	at oracle.jdbc.driver.PhysicalConnection.<init>(PhysicalConnection.java:420)
	at oracle.jdbc.driver.T4CConnection.<init>(T4CConnection.java:165)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:35)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:801)
	at java.sql.DriverManager.getConnection(DriverManager.java:571)
	at java.sql.DriverManager.getConnection(DriverManager.java:215)
	at ru.sns.db.CustConnFactory.getConnection(CustConnFactory.java:101)
	at ru.sns.db.defined.PredefinedConnFactory.open(PredefinedConnFactory.java:352)
	... 10 more
ERROR com.shatura.bc.tmfirst.TerminalSession.run(TerminalSession.java:317) - [01.09.2015 21:07:39]: run()
ru.sns.UnexpectedNestedException: Error while opening connection to wrk;  raiser: ru.sns.db.defined.apps.DatabaseApplEnv$DAEConnFactory, value=ru.sns.db.defined.apps.DatabaseApplEnv$DAEConnFactory@12605d for database named wrk, NESTED: java.sql.SQLException: Io exception: The Network Adapter could not establish the connectionjava.sql.SQLException: Io exception: The Network Adapter could not establish the connection at:
java.sql.SQLException: Io exception: The Network Adapter could not establish the connection
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:112)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:146)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:255)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:387)
	at oracle.jdbc.driver.PhysicalConnection.<init>(PhysicalConnection.java:420)
	at oracle.jdbc.driver.T4CConnection.<init>(T4CConnection.java:165)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:35)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:801)
	at java.sql.DriverManager.getConnection(DriverManager.java:571)
	at java.sql.DriverManager.getConnection(DriverManager.java:215)
	at ru.sns.db.CustConnFactory.getConnection(CustConnFactory.java:101)
	at ru.sns.db.defined.PredefinedConnFactory.open(PredefinedConnFactory.java:352)
	at ru.sns.db.defined.PredefinedConnection.getConnection(PredefinedConnection.java:106)
	at ru.sns.db.defined.DefaultPredefinedConnUser.getConnection(DefaultPredefinedConnUser.java:58)
	at com.shatura.bc.tmfirst.data.db.DataCache.registerSession(DataCache.java:33)
	at com.shatura.bc.tmfirst.logic.DBOpers.registerSession(DBOpers.java:72)
	at com.shatura.bc.tmfirst.logic.acts.GoToMainMenuAction.perform(GoToMainMenuAction.java:21)
	at com.shatura.bc.tmfirst.logic.states.InitialTerminalSessionState.doActionByData(InitialTerminalSessionState.java:28)
	at com.shatura.bc.tmfirst.logic.states.AbstractTerminalSessionState.processData(AbstractTerminalSessionState.java:52)
	at com.shatura.bc.tmfirst.logic.LogicProcessor.process(LogicProcessor.java:70)
	at com.shatura.bc.tmfirst.TerminalSession.run(TerminalSession.java:313)
	at net.wimpi.telnetd.net.Connection.run(Connection.java:125)

	at ru.sns.db.defined.PredefinedConnFactory.open(PredefinedConnFactory.java:354)
	at ru.sns.db.defined.PredefinedConnection.getConnection(PredefinedConnection.java:106)
	at ru.sns.db.defined.DefaultPredefinedConnUser.getConnection(DefaultPredefinedConnUser.java:58)
	at com.shatura.bc.tmfirst.data.db.DataCache.registerSession(DataCache.java:33)
	at com.shatura.bc.tmfirst.logic.DBOpers.registerSession(DBOpers.java:72)
	at com.shatura.bc.tmfirst.logic.acts.GoToMainMenuAction.perform(GoToMainMenuAction.java:21)
	at com.shatura.bc.tmfirst.logic.states.InitialTerminalSessionState.doActionByData(InitialTerminalSessionState.java:28)
	at com.shatura.bc.tmfirst.logic.states.AbstractTerminalSessionState.processData(AbstractTerminalSessionState.java:52)
	at com.shatura.bc.tmfirst.logic.LogicProcessor.process(LogicProcessor.java:70)
	at com.shatura.bc.tmfirst.TerminalSession.run(TerminalSession.java:313)
	at net.wimpi.telnetd.net.Connection.run(Connection.java:125)
Caused by: java.sql.SQLException: Io exception: The Network Adapter could not establish the connection
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:112)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:146)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:255)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:387)
	at oracle.jdbc.driver.PhysicalConnection.<init>(PhysicalConnection.java:420)
	at oracle.jdbc.driver.T4CConnection.<init>(T4CConnection.java:165)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:35)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:801)
	at java.sql.DriverManager.getConnection(DriverManager.java:571)
	at java.sql.DriverManager.getConnection(DriverManager.java:215)
	at ru.sns.db.CustConnFactory.getConnection(CustConnFactory.java:101)
	at ru.sns.db.defined.PredefinedConnFactory.open(PredefinedConnFactory.java:352)
	... 10 more
